Lesson40/code2/MovieWebApp/MovieWebApp/Areas/Admin/Pages/Roles/Create.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MovieWebApp.Models.Admin;

namespace MovieWebApp.Areas.Admin.Pages.Roles;

public class CreateRoleModel : PageModel
{
    private readonly RoleManager<IdentityRole> _roleManager;

    public CreateRoleModel(RoleManager<IdentityRole> roleManager)
    {
        _roleManager = roleManager;
    }

    [BindProperty]
    public RoleCreateModel RoleCreate { get; set; }
    
    public void OnGet()
    {
        
    }
    
    public async Task<IActionResult> OnPostAsync()
    {
        if(!ModelState.IsValid)
        {
            return Page();
        }
        
        var role = new IdentityRole
        {
            Name = RoleCreate.Name,
        };
        var createResult = await _roleManager.CreateAsync(role);
        if(createResult.Succeeded)
        {
            return RedirectToPage("./Index");
        }

        foreach (var identityError in createResult.Errors)
        {
            ModelState.AddModelError("", identityError.Code + ": " + identityError.Description);
        }
        
        return Page();
    }
}

Lesson40/code2/MovieWebApp/MovieWebApp/Areas/Admin/Pages/Users/Create.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MovieWebApp.Models.Admin;

namespace MovieWebApp.Areas.Admin.Pages.Users;

public class CreateModel : PageModel
{
    private readonly UserManager<IdentityUser> _userManager;

    public CreateModel(UserManager<IdentityUser> userManager)
    {
        _userManager = userManager;
    }

    [BindProperty]
    public UserCreateModel UserCreate { get; set; }
    
    public void OnGet()
    {
        
    }
    
    public async Task<IActionResult> OnPostAsync()
    {
        if(!ModelState.IsValid || UserCreate.Password != UserCreate.ConfirmPassword)
        {
            return Page();
        }
        
        var user = new IdentityUser
        {
            UserName = UserCreate.Email,
            Email = UserCreate.Email,
        };
        var createResult = await _userManager.CreateAsync(user, UserCreate.Password);
        if(createResult.Succeeded)
        {
            return RedirectToPage("./Index");
        }

        foreach (var identityError in createResult.Errors)
        {
            ModelState.AddModelError("", identityError.Code + ": " + identityError.Description);
        }
        
        return Page();
    }
}

Lesson40/code2/MovieWebApp/MovieWebApp/Pages/Movies.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MovieWebApp.Pages;

public class MoviesPageModel : PageModel
{
    public void OnGet(string name)
    {
        ViewData["Name"] = name;
    }
}

Lesson40/code2/MovieWebApp/MovieWebApp/Pages/Movies/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using MovieWebApp.Data;
using MovieWebApp.Models;
using MovieWebApp.Models.Dtos;

namespace MovieWebApp.Pages.Movies
{
    [Authorize(Policy = "WithPassport")]
    public class CreateModel : PageModel
    {
        private readonly MovieWebAppContext _context;
        private IWebHostEnvironment _webHostEnvironment;
        private readonly IMapper _mapper;

        public CreateModel(MovieWebAppContext context,
                           IWebHostEnvironment webHostEnvironment,
                           IMapper mapper)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
            _mapper = mapper;
        }
        
        public List<SelectListItem> GenreList { get; set; } = new();

        public IActionResult OnGet()
        {
            var claims = User.Claims;
            
            foreach (Genre genreEnum in Enum.GetValues(typeof(Genre)))
                GenreList.Add(new SelectListItem() { Text = genreEnum.ToString(), Value = ((int)genreEnum). ToString() });
            
            return Page();
        }

        [BindProperty]
        public MovieModel Movie { get; set; }

        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            
            var movie = _mapper.Map<Movie>(Movie);
            
            var folderName = Path.Combine(_webHostEnvironment.WebRootPath, "uploads", "images");
            if(!Directory.Exists(folderName))
            {
                Directory.CreateDirectory(folderName);
            }
            
            var fileName = Guid.NewGuid() + Path.GetExtension(Movie.Image.FileName);
            var fileFullPath = Path.Combine(folderName, fileName);
            
            using (var fileStream = new FileStream(fileFullPath, FileMode.Create))
            {
                await Movie.Image.CopyToAsync(fileStream);
            }

            movie.ImageUrl = fileName;

            _context.Movie.Add(movie);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Lesson40/code2/MovieWebApp/MovieWebApp/Pages/Movies/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MovieWebApp.Data;
using MovieWebApp.Models;

namespace MovieWebApp.Pages.Movies
{
    public class DeleteModel : PageModel
    {
        private readonly MovieWebAppContext _context;

        public DeleteModel(MovieWebAppContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Movie Movie { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Movie = await _context.Movie.FirstOrDefaultAsync(m => m.ID == id);

            if (Movie == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Movie = await _context.Movie.FindAsync(id);

            if (Movie != null)
            {
                _context.Movie.Remove(Movie);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Lesson40/code2/MovieWebApp/MovieWebApp/Pages/Movies/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MovieWebApp.Data;
using MovieWebApp.Models;
using MovieWebApp.Models.Dtos;

namespace MovieWebApp.Pages.Movies
{
    [Authorize(Policy = "WithPassport")]
    public class DetailsModel : PageModel
    {
        private readonly MovieWebAppContext _context;
        private readonly IMapper _mapper;

        public DetailsModel(MovieWebAppContext context,
                            IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }

        public MovieModel Movie { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Movie = _mapper.Map<MovieModel>(await _context.Movie.FirstOrDefaultAsync(m => m.ID == id));

            if (Movie == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

Lesson40/code2/MovieWebApp/MovieWebApp/Pages/Movies/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MovieWebApp.Data;
using MovieWebApp.Models;
using MovieWebApp.Models.Dtos;

namespace MovieWebApp.Pages.Movies
{
    public class EditModel : PageModel
    {
        private readonly MovieWebAppContext _context;
        private readonly IMapper _mapper;
        private readonly IWebHostEnvironment _environment;

        public EditModel(MovieWebAppContext context,
                         IMapper mapper,
                         IWebHostEnvironment environment)
        {
            _context = context;
            _mapper = mapper;
            _environment = environment;
        }
        
        public List<SelectListItem> GenreList { get; set; } = new();

        [BindProperty]
        public MovieModel Movie { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movieEntity = await _context.Movie.FirstOrDefaultAsync(m => m.ID == id);
            
            if (movieEntity == null)
            {
                return NotFound();
            }

            Movie = _mapper.Map<MovieModel>(movieEntity);
            
            foreach (Genre genreEnum in Enum.GetValues(typeof(Genre)))
                GenreList.Add(new SelectListItem() { Text = genreEnum.ToString(), Value = ((int)genreEnum). ToString() });
            
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            
            var movieEntity = _mapper.Map<Movie>(Movie);

            if(Movie.Image != null)
            {
                var directory = Path.Combine(_environment.WebRootPath, "uploads", "images");
                if(Directory.Exists(directory) == false)
                {
                    Directory.CreateDirectory(directory);
                }
                var fileName = Guid.NewGuid().ToString() + Path.GetExtension(Movie.Image.FileName);

                await using (var fileStream = new FileStream(Path.Combine(directory, fileName), FileMode.Create))
                {
                    await Movie.Image.CopyToAsync(fileStream);
                }
                
                movieEntity.ImageUrl = fileName;
            }

            _context.Attach(movieEntity).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!MovieExists(movieEntity.ID))
                {
                    return NotFound();
                }

                throw;
            }

            return RedirectToPage("./Index");
        }

        public async Task<IActionResult> OnPostImageDeleteAsync(int movieId)
        {
            var movieEntity = await _context.Movie.FindAsync(movieId);
            
            if(movieEntity == null) return RedirectToPage("./Index");
            
            var fileFullUrl = Path.Combine(_environment.WebRootPath, "uploads", "images", movieEntity.ImageUrl);
            if(System.IO.File.Exists(fileFullUrl))
            {
                System.IO.File.Delete(fileFullUrl);
            }
            movieEntity.ImageUrl = null;
            _context.Movie.Update(movieEntity);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
        
        private bool MovieExists(int id)
        {
            return _context.Movie.Any(e => e.ID == id);
        }
    }
}

Lesson40/code2/MovieWebApp/MovieWebApp/Pages/Movies/Index.cshtml.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using MovieWebApp.Data;
using MovieWebApp.Models.Dtos;

namespace MovieWebApp.Pages.Movies
{
    [Authorize]
    public class IndexModel : PageModel
    {
        private readonly MovieWebAppContext _context;
        private readonly IMapper _mapper;

        public IndexModel(MovieWebAppContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }

        public IList<MovieModel> Movies { get;set; }

        public async Task OnGetAsync()
        {
            Movies = _mapper.Map<IList<MovieModel>>(await _context.Movie.ToListAsync());
        }
    }
}

Lesson40/code2/MovieWebApp/MovieWebApp/ViewComponents/GenreCountViewComponent.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MovieWebApp.Data;
using MovieWebApp.Models;

namespace MovieWebApp.ViewComponents;

public class GenreCountViewComponent : ViewComponent
{
    private readonly MovieWebAppContext _context;

    public GenreCountViewComponent(MovieWebAppContext context)
    {
        _context = context;
    }
    
    public async Task<IViewComponentResult> InvokeAsync(Genre genre)
    {
        var result = await _context.Movie.Where(m => m.Genre == genre)
                                   .GroupBy(x => x.Genre)
                                   .Select(x => new GenreCountViewModel
                                   {
                                       Genre = x.Key,
                                       Count = x.Count()
                                   }).FirstOrDefaultAsync() ?? new GenreCountViewModel
        {
            Genre = genre,
            Count = 0
        };

        return View(result);
    }
}

Lesson40/code2/MovieWebApp/MovieWebApp/Pages/Movies/Create.cshtml
@page
@model MovieWebApp.Pages.Movies.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create Movie</h1>
<hr/>
<form method="post" enctype="multipart/form-data">
    <div class="row">
        <div class="col-md-7">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group mb-3">
                <label asp-for="Movie.Title" class="control-label"></label>
                <input asp-for="Movie.Title" class="form-control"/>
                <span asp-validation-for="Movie.Title" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="Movie.ReleaseDate" class="control-label"></label>
                <input asp-for="Movie.ReleaseDate" class="form-control"/>
                <span asp-validation-for="Movie.ReleaseDate" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="Movie.Genre" class="control-label"></label>
                <select asp-for="Movie.Genre" class="form-select" asp-items="Model.GenreList">
                    <option>Not Selected</option>
                </select>
                <span asp-validation-for="Movie.Genre" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="Movie.Price" class="control-label"></label>
                <input asp-for="Movie.Price" class="form-control"/>
                <span asp-validation-for="Movie.Price" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="Movie.Description" class="control-label"></label>
                <textarea rows="6" asp-for="Movie.Description" class="form-control"></textarea>
                <span asp-validation-for="Movie.Description" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <input type="submit" value="Create" class="btn btn-primary"/>
            </div>
        </div>
        <div class="col-md-5">
            <div class="form-group">
                <img width="300" height="300" id="imgPreview" src="https://fakeimg.pl/300x300/?text=Movie Image" alt="Movie Image"/>
                <br/>
                <br/>
                <input type="file" id="inputFile" asp-for="Movie.Image"/>
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-page="Index">Back to List</a>
</div>


@section Scripts {
    <script>
        $(document).ready(function () {
            $("#inputFile").change(function () {
                const file = this.files[0];
                const reader = new FileReader();
                reader.onload = function (e) {
                    $("#imgPreview").attr("src", e.target.result);
                }
                reader.readAsDataURL(file);
            });
        });
    </script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Lesson40/code2/MovieWebApp/MovieWebApp/Pages/Movies/Delete.cshtml
@page
@model MovieWebApp.Pages.Movies.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Movie</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Movie.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Movie.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Movie.ReleaseDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Movie.ReleaseDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Movie.Genre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Movie.Genre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Movie.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Movie.Price)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Movie.ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

Lesson40/code2/MovieWebApp/MovieWebApp/Pages/Movies/Details.cshtml
@page "view/{id}"
@using MovieWebApp.ViewComponents
@model MovieWebApp.Pages.Movies.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>
<div class="row">
    <div class="col-9">
        @await Html.PartialAsync("_MovieDetails", Model)
    </div>
    <div class="col-3 mt-lg-5">
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">Genre Count Info</h5>
                <vc:genre-count genre="@Model.Movie.Genre"></vc:genre-count>
                @* @await Component.InvokeAsync("GenreCount", new { genre = Model.Movie.Genre }) *@
            </div>
        </div>
    </div>
</div>

<div>
    <a asp-page="./Edit" asp-route-id="@Model.Movie.ID">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

Lesson40/code2/MovieWebApp/MovieWebApp/Pages/Movies/Edit.cshtml
@page "{id}/{name?}"
@model MovieWebApp.Pages.Movies.EditModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit Movie</h1>
<hr/>
<form method="post" enctype="multipart/form-data">
    <div class="row">
        <div class="col-md-7">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Movie.ID"/>
            <div class="form-group mb-3">
                <label asp-for="Movie.Title" class="control-label"></label>
                <input asp-for="Movie.Title" class="form-control"/>
                <span asp-validation-for="Movie.Title" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="Movie.ReleaseDate" class="control-label"></label>
                <input asp-for="Movie.ReleaseDate" class="form-control"/>
                <span asp-validation-for="Movie.ReleaseDate" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="Movie.Genre" class="control-label"></label>
                <select asp-for="Movie.Genre" class="form-select" asp-items="Model.GenreList">
                    <option>Not Selected</option>
                </select>
                <span asp-validation-for="Movie.Genre" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="Movie.Price" class="control-label"></label>
                <input asp-for="Movie.Price" class="form-control"/>
                <span asp-validation-for="Movie.Price" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <label asp-for="Movie.Description" class="control-label"></label>
                <textarea rows="6" asp-for="Movie.Description" class="form-control"></textarea>
                <span asp-validation-for="Movie.Description" class="text-danger"></span>
            </div>
            <div class="form-group mb-3">
                <input type="submit" value="Save" class="btn btn-primary"/>
            </div>
        </div>
        <div class="col-md-5">
            <div class="form-group">
                <img width="300" height="300" id="imgPreview" 
                      src='@(Model.Movie.ImageUrl == null 
                                                   ? $"https://fakeimg.pl/300x300/?text={Model.Movie.Title}"
                                                   : "/uploads/images/" + Model.Movie.ImageUrl)'
                     alt="@Model.Movie.Title"/>
                <br/>
                <br/>
                <input type="file" id="inputFile" asp-for="Movie.Image"/>
                <br/>
                <button condition="@(Model.Movie.ImageUrl != null)" class="btn btn-danger" asp-route-movieId="@Model.Movie.ID" 
                        asp-page-handler="ImageDelete">Delete Image</button>
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
        <script>
            $(document).ready(function () {
                $("#inputFile").change(function () {
                    const file = this.files[0];
                    const reader = new FileReader();
                    reader.onload = function (e) {
                        $("#imgPreview").attr("src", e.target.result);
                    }
                    reader.readAsDataURL(file);
                });
            });
        </script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Lesson40/code2/MovieWebApp/MovieWebApp/Pages/Movies/Index.cshtml
@page "/Movies/List"
@model MovieWebApp.Pages.Movies.IndexModel

@{
    ViewData["Title"] = "Index";
}

<p>
    <a asp-page="Create">Create New</a>
    <a asp-page="/Movies" asp-route-name="Test" class="float-end">Go to new page</a>
</p>
<div class="row">
    @foreach (var movie in Model.Movies)
    {
        <div class="col-4">
            <div class="card mb-2">
                <img class="card-img-top" width="300" height="300" 
                     src='@(movie.ImageUrl == null 
                              ? $"https://fakeimg.pl/300x300/?text={movie.Title}"
                              : "/uploads/images/" + movie.ImageUrl)'
                     alt="@movie.Title">
                <div class="card-body">
                    <h5 class="card-title">
                        @movie.Title <span style="font-size: 14px;" class="float-right">@movie.ReleaseDate.Year</span>
                    </h5>
                    <p class="card-text" style="height: 200px; overflow-y: auto">
                        <span>
                            <span>
                                <b>@Html.DisplayNameFor(x => movie.Genre):</b>
                            </span>
                            <span>@movie.Genre</span>
                        </span>
                        <br/>
                        <span>
                            <span>
                                <b>@Html.DisplayNameFor(x => movie.Price):</b>
                            </span>
                            <span>@movie.Price</span>
                        </span>
                        <br/>
                        <span>@movie.Description</span>
                    </p>
                      <a class="btn btn-primary" asp-page="./Edit" asp-route-id="@movie.ID" asp-route-name="@movie.Title">Edit</a> 
                      <a class="btn btn-info" asp-page="./Details" asp-route-id="@movie.ID">Details</a> 
                      <a class="btn btn-danger" asp-page="./Delete" asp-route-id="@movie.ID">Delete</a>
                </div>
            </div>
        </div>
    }

</div>
<table class="table table-bordered" condition="false">
    <thead>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Movies[0].Title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Movies[0].ReleaseDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Movies[0].Genre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Movies[0].Price)
        </th>
        <th></th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model.Movies)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReleaseDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                <a asp-page="./Edit" asp-route-id="@item.ID" asp-route-name="@item.Title">Edit</a> |
                <a asp-page="./Details" asp-route-id="@item.ID">Details</a> |
                <a href="Details/view/@item.ID">Details2</a> |
                <a asp-page="./Delete" asp-route-id="@item.ID">Delete</a>
            </td>
        </tr>
    }
    </tbody>
</table>

Lesson40/code2/MovieWebApp/MovieWebApp/Pages/Movies/_MovieDetails.cshtml
@model MovieWebApp.Pages.Movies.DetailsModel

<div>
    <h4>Movie</h4>
    <hr/>
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Movie.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Movie.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Movie.ReleaseDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Movie.ReleaseDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Movie.Genre)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Movie.Genre)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Movie.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Movie.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Movie.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Movie.Description)
        </dd>
    </dl>
</div>
<div class="row">
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Movie.Image)
    </dt>
    <dd class="col-sm-10">
        <img width="300" height="300" id="imgPreview"
             src='@(Model.Movie.ImageUrl == null ? $"https://fakeimg.pl/300x300/?text={Model.Movie.Title}" : "/uploads/images/" + Model.Movie.ImageUrl)'
             alt="@Model.Movie.Title"/>
    </dd>
</div>