Lesson40/code2/MovieWebApp/MovieWebApp/ViewComponents/FooterViewComponent.cs
using System.IO;
using Microsoft.AspNetCore.Mvc;
using MovieWebApp.Models;

namespace MovieWebApp.ViewComponents;

public class FooterViewComponent : ViewComponent
{
    public IViewComponentResult Invoke()
    {
        var lastUpdated = new FileInfo(typeof(Startup).Assembly.Location).LastWriteTime;
        return View(new FooterViewModel
        {
            LastUpdatedTime = lastUpdated
        });
    }
}

Lesson40/code2/MovieWebApp/MovieWebApp/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - MovieWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
    <link rel="stylesheet" href="~/MovieWebApp.styles.css"/>
</head>
<body>
<header>
    @await Html.PartialAsync("_MenuBar")
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>
@await Component.InvokeAsync("Footer", new { Test = 123 })

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>

@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Lesson40/code2/MovieWebApp/MovieWebApp/Pages/Shared/_MenuBar.cshtml
@using Microsoft.AspNetCore.Identity
@using Microsoft.AspNetCore.Mvc.TagHelpers
@inject SignInManager<IdentityUser> SignInManager

<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
    <div class="container">
        <a class="navbar-brand" asp-area="" asp-page="/Index">MovieWebApp</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                </li>
                @if (SignInManager.IsSignedIn(User))
                {
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-page="/Movies/Index">Movies</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="Admin" asp-page="/Users/Index">Admin</a>
                    </li>
                }
            </ul>
            <partial name="_LoginPartial"/>
        </div>
    </div>
</nav>